"""
Test fixtures for PH Geospatial Platform.

Five synthetic GeoParquet files covering Philippine administrative boundaries.
Generated by generate_fixtures.py; committed to repo for CI reproducibility.
"""
